name: Deploy to gh pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  check-success:
    runs-on: ubuntu-latest
    needs: [ build, deploy ]
    if: ${{ !failure() && !cancelled() }}
    steps:
      - name: send telegram message on success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_DEPLOY_GROUP_ID }}
          token: ${{ secrets.TG_DEPLOY_BOT_TOKEN }}
          message: |
           🟢 Changes from by ${{ github.actor }} from commit: ${{ github.event.commits[0].message }}
            repository: ${{ github.repository }}
            has been deployed successfully on https://zomurrod.com

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  check-failure:
    runs-on: ubuntu-latest
    needs: [ build, deploy ]
    if: ${{ failure() }}
    steps:
      - name: send telegram message on failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_DEPLOY_GROUP_ID }}
          token: ${{ secrets.TG_DEPLOY_BOT_TOKEN }}
          message: |
            ❌ Failed to deploy changes from ${{ github.actor }} from commit: ${{ github.event.commits[0].message }}
            on Repository: ${{ github.repository }}

            see changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

            failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
